name: Build CN ASN (mrs)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *" 

permissions:
  contents: write

concurrency:
  group: cn-asn
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build ASN
        run: node scripts/convert.js

      - name: Build MRS
        run: |
          set -e
          curl -L https://github.com/DustinWin/proxy-tools/releases/download/mihomo/mihomo-meta-linux-amd64v3.tar.gz | tar -zx
          mv CrashCore mihomo
          chmod +x mihomo
          test -s CN_ASN_No_Resolve.list
          ./mihomo convert-ruleset asn text CN_ASN_No_Resolve.list CN_ASN_No_Resolve.mrs

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add CN_ASN.mrs
          git commit -m "update CN ASN ($(date -u '+%Y-%m-%d %H:%M UTC'))" || echo "no change"
          git push
