
concurrency:
  group: cn-asn
  cancel-in-progress: true

name: Build CN ASN

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build ASN
        run: node scripts/convert.js
      
      - name: Build MRS
        run: |
          wget https://github.com/MetaCubeX/mihomo/releases/latest/download/mihomo-linux-amd64 -O mihomo
          chmod +x mihomo
          ./mihomo rule-set compile CN_ASN.yaml CN_ASN.mrs
          ./mihomo rule-set compile CN_ASN_No_Resolve.yaml CN_ASN_No_Resolve.mrs

- name: Commit changes
  run: |
    git config user.name "github-actions"
    git config user.email "github-actions@github.com"
    git add .
    git commit -m "update CN ASN ($(date -u '+%Y-%m-%d %H:%M UTC'))" || echo "no change"
    git push

